import type { Metadata } from "next";
import { GeistSans, GeistMono } from "geist/font";
import "../globals.css";
import { Sidebar } from "@/components/ui/sidebar";
import NavBar from "@/components/ui/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body className={`${GeistSans.variable} ${GeistMono.variable} antialiased overflow-x-hidden`}>
        <div className="flex w-screen">
          <div className="w-[20%]">
            <Sidebar />
          </div>
          <div className="w-[80%]">
            <div className="border-b border-[#dbdadd]">
              <NavBar />
            </div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
