"use client"

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"

export default function DailyReports() {
  return (
    <div className="p-8 space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Daily Revenue Report</CardTitle>
          <CardDescription>Today's financial performance</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="p-4 bg-gradient-to-br from-green-50 to-green-100 rounded-lg border border-green-200">
              <p className="text-sm text-green-600 font-medium">Total Revenue</p>
              <p className="text-3xl font-bold text-green-900 mt-2">$45,820</p>
              <p className="text-xs text-green-600 mt-1">+12.5% vs yesterday</p>
            </div>
            <div className="p-4 bg-gradient-to-br from-blue-50 to-blue-100 rounded-lg border border-blue-200">
              <p className="text-sm text-blue-600 font-medium">Bookings Completed</p>
              <p className="text-3xl font-bold text-blue-900 mt-2">342</p>
              <p className="text-xs text-blue-600 mt-1">18 more than avg</p>
            </div>
            <div className="p-4 bg-gradient-to-br from-purple-50 to-purple-100 rounded-lg border border-purple-200">
              <p className="text-sm text-purple-600 font-medium">Active Transactions</p>
              <p className="text-3xl font-bold text-purple-900 mt-2">$2.3M</p>
              <p className="text-xs text-purple-600 mt-1">Processing now</p>
            </div>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Top Performing Agents</CardTitle>
          <CardDescription>Revenue generated by agent</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {[
              { agent: "John Smith", revenue: "$8,450", bookings: 45 },
              { agent: "Sarah Johnson", revenue: "$7,230", bookings: 38 },
              { agent: "Mike Davis", revenue: "$6,890", bookings: 35 },
              { agent: "Emma Wilson", revenue: "$5,450", bookings: 28 },
            ].map((item, idx) => (
              <div
                key={idx}
                className="flex items-center justify-between p-3 border border-border rounded-lg hover:bg-muted/50"
              >
                <div className="flex-1">
                  <p className="font-medium">{item.agent}</p>
                  <p className="text-sm text-muted-foreground">{item.bookings} bookings</p>
                </div>
                <p className="font-bold text-lg">{item.revenue}</p>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
